### PR TITLE
Regenerate

### PR DESCRIPTION
**Pull request by YuriGor**

### CODE REVIEW

**Comment by wooorm** [comment]
@YuriGor Thanks for working on this. github/gemoji is about to get a major release, but I’m not entirely sure what they’re waiting on.
I’d like to wait on them releasing the emoji though, before releasing a major here.

**Comment by YuriGor** [comment]
Ok, and what about indexing by tag/category?

**Comment by YuriGor** [comment]
Oh, I see Travis is complaining about no forEach, I will fix it soon.

**Comment by YuriGor** [comment]
Something is wrong with 🏎 and 🏍 after regeneration
It's impossible to find them in the unicode index.
while this function:
```js
const toUni = function(str) {
  if (str.length < 4) return str.codePointAt(0).toString(16);
  return (
    str.codePointAt(0).toString(16) + '-' + str.codePointAt(2).toString(16)
  );
};
```
still returns identical result both for 🏎 and the key from unicode index.
other emojies looks like work well.

**Comment by YuriGor** [comment]
here we go
https://mothereff.in/js-escapes#1%F0%9F%8F%8E-%F0%9F%8F%8E%EF%B8%8F
racing_car in the most recent gemoji json is represented by three escape instead of two as it used to be.

**Comment by YuriGor** [comment]
I opened an [issue there](https://github.com/github/gemoji/issues/163)

**Comment by wooorm** [comment]
Thanks for working on that issue there! I’m glad you found that “wrong” codepoints bug before the major went out!

I’d still like to wait on a major btw!

> Ok, and what about indexing by tag/category?

I think that’s a useful thing to have, but I think that’s better in a different project. That way we can keep `wooorm/gemoji` smaller and to use less memory. Because not everyone needs it!

**Comment by YuriGor** [comment]
Finally I've decided to generate my own emoji list parsed from unicode.org, so i have no more need in this PR, thank you for inspiration)

**Pull request closed without merging**
